#include "scope.h"

void SymbolVisitor::Visit(Crate *crate_ptr) {}
void SymbolVisitor::Visit(Item *item_ptr) {}
void SymbolVisitor::Visit(Function *function_ptr) {}
void SymbolVisitor::Visit(Struct *struct_ptr) {}
void SymbolVisitor::Visit(Enumeration *enumeration_ptr) {}
void SymbolVisitor::Visit(ConstantItem *constant_item_ptr) {}
void SymbolVisitor::Visit(Trait *trait_ptr) {}
void SymbolVisitor::Visit(Implementation *implementation_ptr) {}
void SymbolVisitor::Visit(Keyword *keyword_ptr) {}
void SymbolVisitor::Visit(Identifier *identifier_ptr) {}
void SymbolVisitor::Visit(Punctuation *punctuation_ptr) {}
void SymbolVisitor::Visit(FunctionParameters *function_parameters_ptr) {}
void SymbolVisitor::Visit(FunctionReturnType *function_return_type_ptr) {}
void SymbolVisitor::Visit(BlockExpression *block_expression_ptr) {}
void SymbolVisitor::Visit(SelfParam *self_param_ptr) {}
void SymbolVisitor::Visit(FunctionParam *function_param_ptr) {}
void SymbolVisitor::Visit(ShorthandSelf *shorthand_self_ptr) {}
void SymbolVisitor::Visit(TypedSelf *typed_self_ptr) {}
void SymbolVisitor::Visit(Type *type_ptr) {}
void SymbolVisitor::Visit(Pattern *pattern_ptr) {}
void SymbolVisitor::Visit(WildcardPattern *wildcard_pattern_ptr) {}
void SymbolVisitor::Visit(ReferencePattern *reference_pattern_ptr) {}
void SymbolVisitor::Visit(IdentifierPattern *identifier_pattern_ptr) {}
void SymbolVisitor::Visit(LiteralPattern *literal_pattern_ptr) {}
void SymbolVisitor::Visit(PathInExpression *path_in_expression_ptr) {}
void SymbolVisitor::Visit(LiteralExpression *literal_expression_ptr) {}
void SymbolVisitor::Visit(PathExprSegment *path_expr_segment_ptr) {}
void SymbolVisitor::Visit(ReferenceType *reference_type_ptr) {}
void SymbolVisitor::Visit(ArrayType *array_type_ptr) {}
void SymbolVisitor::Visit(TypePath *type_path_ptr) {}
void SymbolVisitor::Visit(UnitType *unit_type_ptr) {}
void SymbolVisitor::Visit(Expression *expression_ptr) {}
void SymbolVisitor::Visit(Statements *statements_ptr) {}
void SymbolVisitor::Visit(Statement *statement_ptr) {}
void SymbolVisitor::Visit(LetStatement *let_statement_ptr) {}
void SymbolVisitor::Visit(ExpressionStatement *expression_statement_ptr) {}
void SymbolVisitor::Visit(StructExprFields *struct_expr_fields_ptr) {}
void SymbolVisitor::Visit(StructExprField *struct_expr_field_ptr) {}
void SymbolVisitor::Visit(CharLiteral *char_literal_ptr) {}
void SymbolVisitor::Visit(StringLiteral *string_literal_ptr) {}
void SymbolVisitor::Visit(RawStringLiteral *raw_string_literal_ptr) {}
void SymbolVisitor::Visit(CStringLiteral *c_string_literal_ptr) {}
void SymbolVisitor::Visit(RawCStringLiteral *raw_c_string_literal_ptr) {}
void SymbolVisitor::Visit(IntegerLiteral *integer_literal_ptr) {}
void SymbolVisitor::Visit(StructFields *struct_fields_ptr) {}
void SymbolVisitor::Visit(StructField *struct_field_ptr) {}
void SymbolVisitor::Visit(EnumVariants *enum_variants_ptr) {}
void SymbolVisitor::Visit(AssociatedItem *associated_item_ptr) {}