#ifndef CLASSES_H
#define CLASSES_H

class Node;
class LeafNode;
class Crate;
class Item;
class Function;
class Struct;
class Enumeration;
class ConstantItem;
class Trait;
class Implementation;
class Keyword;
class Identifier;
class Punctuation;
class FunctionParameters;
class FunctionReturnType;
class BlockExpression;
class SelfParam;
class FunctionParam;
class ShorthandSelf;
class TypedSelf;
class Type;
class Pattern;
class WildcardPattern;
class ReferencePattern;
class IdentifierPattern;
class LiteralPattern;
class PathInExpression;
class LiteralExpression;
class PathExprSegment;
class ReferenceType;
class ArrayType;
class TypePath;
class UnitType;
class Expression;
class Statements;
class Statement;
class LetStatement;
class ExpressionStatement;
class StructExprFields;
class StructExprField;
class CharLiteral;
class StringLiteral;
class RawStringLiteral;
class CStringLiteral;
class RawCStringLiteral;
class IntegerLiteral;
class StructFields;
class StructField;
class EnumVariants;
class AssociatedItem;
class Visitor;
class SymbolVisitor;

#endif