#include "IR_generator.h"

void IRVisitor::Visit(Crate *crate_ptr) {}
void IRVisitor::Visit(Item *item_ptr) {}
void IRVisitor::Visit(Function *function_ptr) {}
void IRVisitor::Visit(Struct *struct_ptr) {}
void IRVisitor::Visit(Enumeration *enumeration_ptr) {}
void IRVisitor::Visit(ConstantItem *constant_item_ptr) {}
void IRVisitor::Visit(Trait *trait_ptr) {}
void IRVisitor::Visit(Implementation *implementation_ptr) {}
void IRVisitor::Visit(Keyword *keyword_ptr) {}
void IRVisitor::Visit(Identifier *identifier_ptr) {}
void IRVisitor::Visit(Punctuation *punctuation_ptr) {}
void IRVisitor::Visit(FunctionParameters *function_parameters_ptr) {}
void IRVisitor::Visit(FunctionReturnType *function_return_type_ptr) {}
void IRVisitor::Visit(BlockExpression *block_expression_ptr) {}
void IRVisitor::Visit(SelfParam *self_param_ptr) {}
void IRVisitor::Visit(FunctionParam *function_param_ptr) {}
void IRVisitor::Visit(ShorthandSelf *shorthand_self_ptr) {}
void IRVisitor::Visit(Type *type_ptr) {}
void IRVisitor::Visit(Pattern *pattern_ptr) {}
void IRVisitor::Visit(ReferencePattern *reference_pattern_ptr) {}
void IRVisitor::Visit(IdentifierPattern *identifier_pattern_ptr) {}
void IRVisitor::Visit(PathInExpression *path_in_expression_ptr) {}
void IRVisitor::Visit(PathExprSegment *path_expr_segment_ptr) {}
void IRVisitor::Visit(ReferenceType *reference_type_ptr) {}
void IRVisitor::Visit(ArrayType *array_type_ptr) {}
void IRVisitor::Visit(TypePath *type_path_ptr) {}
void IRVisitor::Visit(UnitType *unit_type_ptr) {}
void IRVisitor::Visit(Expression *expression_ptr) {}
void IRVisitor::Visit(Statements *statements_ptr) {}
void IRVisitor::Visit(Statement *statement_ptr) {}
void IRVisitor::Visit(LetStatement *let_statement_ptr) {}
void IRVisitor::Visit(ExpressionStatement *expression_statement_ptr) {}
void IRVisitor::Visit(StructExprFields *struct_expr_fields_ptr) {}
void IRVisitor::Visit(StructExprField *struct_expr_field_ptr) {}
void IRVisitor::Visit(CharLiteral *char_literal_ptr) {}
void IRVisitor::Visit(StringLiteral *string_literal_ptr) {}
void IRVisitor::Visit(RawStringLiteral *raw_string_literal_ptr) {}
void IRVisitor::Visit(CStringLiteral *c_string_literal_ptr) {}
void IRVisitor::Visit(RawCStringLiteral *raw_c_string_literal_ptr) {}
void IRVisitor::Visit(IntegerLiteral *integer_literal_ptr) {}
void IRVisitor::Visit(StructFields *struct_fields_ptr) {}
void IRVisitor::Visit(StructField *struct_field_ptr) {}
void IRVisitor::Visit(EnumVariants *enum_variants_ptr) {}
void IRVisitor::Visit(AssociatedItem *associated_item_ptr) {}