name: CMake CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install GCC 13
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-13 g++-13
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 13
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 13

      - name: Verify testcases directory
        run: |
          ls -la RCompiler-Testcases/
          echo "Testcases directory verified"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtest-dev libboost-all-dev

      - name: Build and install GTest
        run: |
          cd /usr/src/googletest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp lib/*.a /usr/lib

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}}

#      - name: Build
#        run: cmake --build ${{github.workspace}}/build --config Release
      - name: Build and Test
        run: |
          # 显示详细文件结构
          find . -name "*.cpp" -o -name "*.h" | sort
          # 显示文件大小写
          ls -la lexer/src/
          ls -la parser/src/  
          ls -la semantic/src/
          # 详细构建输出
          cmake -B build -DCMAKE_VERBOSE_MAKEFILE=ON
          cmake --build build --verbose

      - name: Run tests
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure

      - name: Run semantic tests
        run: |
          g++ -std=c++20 -I./lexer/include -I./parser/include -I./semantic/include \
              ./test/test.cpp -o semantic_test \
              -lgtest -lgtest_main -lpthread
          ./semantic_test --gtest_output="xml:semantic_test_results.xml"