name: CMake CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Verify testcases directory
        run: |
          ls -la RCompiler-Testcases/
          echo "Testcases directory verified"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libgtest-dev libboost-all-dev

      - name: Build and install GTest
        run: |
          cd /usr/src/googletest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp lib/*.a /usr/lib

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Run tests
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure

      - name: Run semantic tests
        run: |
          echo "Compiling semantic test program..."
          g++ -std=c++20 -I./lexer/include -I./parser/include -I./semantic/include \
              ./test/test.cpp -o semantic_test \
              -lgtest -lgtest_main -lpthread
          
          echo "Running semantic tests..."
          ./semantic_test --gtest_output="xml:semantic_test_results.xml"
          
          echo "Semantic tests completed. Results saved to semantic_test_results.xml"