name: CI
on: [push, pull_request]  # 触发条件

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # 也可选 windows-latest/macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libgtest-dev

      - name: Build and Run Tests
        run: |
          mkdir build && cd build
          cmake .. -DBUILD_TESTS=ON  # 启用测试
          make
          ctest --output-on-failure   # 运行测试并显示详细失败信息

      - name: Upload Test Results (可选)
        if: always()  # 即使测试失败也上传
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/Testing/**/*.xml  # 捕获 JUnit 格式报告